# NVIDIA NeMo Agent Toolkit 黑客松配置
# 支持用户自定义OpenAI兼容API

general:
  use_uvloop: true

functions:
  tavily_search:
    _type: tavily_internet_search
    description: "使用Tavily API进行实时网络搜索"
  
  current_datetime:
    _type: current_datetime
    description: "获取当前日期和时间"

  ip_obtain:
    _type: ip_obtain
    description: "获取当前机器的公网IP地址"

  current_location:
    _type: current_location
    description: "获取IP对应的地理位置信息"

  lianjia_scraper:
    _type: lianjia_scraper
    description: "采集链家房产API数据，可输出JSON格式"
    # Default configuration for lianjia scraper
    city: "sh"
    max_requests: 5
   
  json_fetch_tool:
    _type: json_fetch_tool
    description: "采集链家新房数据并导出 JSON 文件"
    # Default configuration for JSON fetch tool
    base_url: "https://sh.fang.lianjia.com/loupan/pg{page}/?_t=1/"
    max_pages: 5
    delay_seconds: 1.0
    export_dir: "./data"

llms:
  # 默认使用ModelScope API (用户可修改)
  default_llm:
    _type: openai
    model_name: "qwen3:30b"
    api_key: "ollama"
    base_url: "http://localhost:11434/v1/"
    temperature: 0.7
    max_tokens: 2048

workflow:
  _type: react_agent
  tool_names:
    - ip_obtain
    - current_location
    - lianjia_scraper
    - json_fetch_tool
    # - tavily_search
    # - current_datetime
  llm_name: default_llm
  verbose: true
  parse_agent_response_max_retries: 3
  max_iterations: 10
